version: '3.4'
services:
  phx:
    container_name: umbrella
    build:
      context: .
    ports:
     - "4000:4000"
    volumes:
      - type: bind
        source: "."
        target: /app

    command: |
      bash -c '
        set -e

        mix deps.get || true # do not fail when no network

        bash
        '
    stdin_open: true
    tty: true

